### ISSUE TITLE
Add US-RSE DEI Speaker Series Event

### ISSUE THREAD

**Issue by mrmundt** [DiveRSE-RSE/DiveRSE-RSE.github.io#2]
The US-RSE has a DEI Speaker Series event that is taking place tomorrow. Link to the event is here: https://us-rse.org/events/2022/2022-03-dei-speaker-series/

We would like to add this event and our future events to the DiveRSE website - and happy to help set up the structure to add events! Please let us know how we can help.

**Comment by jcohen02** [comment]
Thanks for opening this @mrmundt and apologies for it getting lost for such a long time! I know we missed the talk taking place straight after this issue was opened. We can certainly add that as a past event if it's useful to maintain a record of it.

Otherwise, very happy to have US-RSE DEI talks added to the event list. Maybe we can come up with some sort of simple badging approach or similar where we can highlight in our event list talks taking place in partner or related series by different badges or icons.

At the moment, if you have a title, abstract and speaker bio plus, optionally, a photo, you're welcome to open a PR with a new event page to advertise upcoming US-RSE DEI Speaker Series events. See one of our previous events for a template if that's helpful, e.g. [2022-05-04.md](https://github.com/DiveRSE-RSE/DiveRSE-RSE.github.io/blob/main/_pages/events/2022-05-04.md)

Thanks and apologies once again for the delay on this.

**Comment by mrmundt** [comment]
@jcohen02 - No problem! We have a talk coming up early next month, so I'll open a PR for it. I appreciate the work you've put into this!

**Comment by jcohen02** [comment]
Thanks @mrmundt.
